{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gitee.jicg",
    "module": "btprint-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "btprint-sdk-1.0.0.aar",
          "url": "btprint-sdk-1.0.0.aar",
          "size": 125543,
          "sha512": "8ffa13b2a2291603f9e7cbb0bc98cb51212813bbd12e92bb4b4ab37fd4419ebca21197e96f4e9fb09a80ccd873562143c0782f7564e6dac1989caf3ee17d728d",
          "sha256": "6071d7dd76534dafbc3e3989ea411fdc8f78e8fc151def329db367005451416b",
          "sha1": "194b0ca54716ec71971a289d54791138ba0a81fd",
          "md5": "a0e1d9eff4971656195a12fea794338d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "btprint-sdk-1.0.0.aar",
          "url": "btprint-sdk-1.0.0.aar",
          "size": 125543,
          "sha512": "8ffa13b2a2291603f9e7cbb0bc98cb51212813bbd12e92bb4b4ab37fd4419ebca21197e96f4e9fb09a80ccd873562143c0782f7564e6dac1989caf3ee17d728d",
          "sha256": "6071d7dd76534dafbc3e3989ea411fdc8f78e8fc151def329db367005451416b",
          "sha1": "194b0ca54716ec71971a289d54791138ba0a81fd",
          "md5": "a0e1d9eff4971656195a12fea794338d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "btprint-sdk-1.0.0-sources.jar",
          "url": "btprint-sdk-1.0.0-sources.jar",
          "size": 38593,
          "sha512": "5e87abb7196a659eab448cb9a8f76320124ac8d4324972752a57cf187d75d00d48e07e24f167a7681cb374aea09b29e020d3f354ceef4cd9f9d9993e8fd30074",
          "sha256": "7f0dd94c2a57b38a423245631c3f997a4d69ebb9ba7f7dcf386bf6429a7be623",
          "sha1": "ba526f99dcc436fadf0dfce4efab667d873519ab",
          "md5": "9520210112118937a2d0c54bf2ad9306"
        }
      ]
    }
  ]
}
